### PR TITLE
Resolve #23 with way to override Maven phases/goals

### LINKED ISSUE #23: Override the maven goal sequence with a with: mvn-goals option
Sometime the repository use specific plugins which requires specific goals to be activiated.

For example:
https://github.com/NASA-PDS/api-search-query-lexer

Is build with sequence:

mvn clean antlr4:antlr4 deploy

We want to add an option:

with:
   mvn-goals: clean antlr4:antlr4 deploy

Which will override the current default goals sequence

### PR DESCRIPTION
**Pull request by nutjob4life**
## 📜 Summary

Fix #23 so that you can override the phases and/or goals the Roundup uses when invoking Maven at various points.

## 🩺 Test Data and/or Report

There's no way to test this without a massive test harness (which would include: GitHub Actions ecosystem, actions runners, virtual machines, public key infrastructure, OSSRH stub, PyPI stub, etc.).

## 🧩 Related Issues

- #23

### CODE REVIEW

**Comment by jordanpadams** [comment]
@tloubrieu-jpl give this a test drive per whichever repo you were trying to use this and let's see how it goes

**Comment by tloubrieu-jpl** [comment]
@nutjob4life @jordanpadams  I have bug since the update apparently.

CRITICAL:pds.roundup.util:📚 Stderr = «»
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pds.roundup-0.0.0-py3.8.egg/pds/roundup/util.py", line 45, in invoke
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mvn', '']' returned non-zero exit status 1.

On action https://github.com/NASA-PDS/pds-registry-app/runs/1645833559?check_suite_focus=true

I tried to explicitly have the maven goals as specified in the roundup readme but that did not help.

**Comment by nutjob4life** [comment]
@tloubrieu-jpl could I see your workflow's yaml file?

**Comment by tloubrieu-jpl** [comment]
Hi @nutjob4life 
I retested with this workflow https://github.com/NASA-PDS/pds-registry-app/blob/master/.github/workflows/unstable-cicd.yaml

and had the same error as yesterday.

**Comment by nutjob4life** [comment]
Thanks @tloubrieu-jpl; I'm going to re-open #23

**Pull request merged**
